# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Local

steps:

- script: |
    bash ./misc/build.sh
  displayName: 'Build'

- script: |
    bash ./misc/test.sh
  displayName: 'Test'
